# Generated by Django 3.2.6 on 2022-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220526_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(help_text='Breve informacion', max_length=200),
        ),
    ]
