# Generated by Django 3.2.6 on 2022-05-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='e3',
            field=models.ForeignKey(default='3', help_text='EVENTO 1', on_delete=django.db.models.deletion.CASCADE, related_name='E3', to='blog.eventos'),
        ),
    ]
